server:
  port: 4040
  context-path: /sso1

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

security:
  oauth2:
    client:
      client-id: ezh
      client-secret: ezh
      user-authorization-uri: http://localhost:3000/oauth/authorize
      access-token-uri: http://localhost:3000/oauth/token
      scope: server
    resource:
      jwt:
        key-uri: http://localhost:3000/oauth/token_key

spring:
  application:
    name: ezh-sso-client-demo
  profiles:
    active: dev
  redis:
    remote: true        #是否是cachecloud 获取
    host: 106.14.69.75
    port: 6381
    password:

logging:
  config: classpath:logback.xml
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://ezh:solor@localhost:1025/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://ezh:solor@eureka:1025/eureka
