server:
  port: 4001

spring:
  application:
    name: ezh-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hellohcq/ezh-config.git
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://ezh:solor@localhost:1025/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://ezh:solor@eureka:1025/eureka
